[package]
name = "ccxtr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
hyper = "0.14.26"
thiserror = "1.0.40"
tokio = { version = "1.28.0", features = ["full"] }
